#!/bin/bash -x
check=1
randomCheck=$((RANDOM%2))
headValue=0
tailValue=0
count=1
declare -a times
declare -a timesTriplet
declare -A singlet
declare -A doublet
declare -A triplet
while [ $count -gt 0 ]
do
     for ((i=1; i<=5; i++))
     do
         if [ $check -eq $randomCheck ]
         then
              headValue=$(($headValue+1))
              singlet[$(($i+1))]=$headValue
         else
              tailValue=$(($tailValue+1))
              singlet[$(($i+1))]=$tailValue
         fi
      ((count++))
    done
done
echo "${singlet[@]}"
singlet_percentage=$(((1/2)*100))
for ((i=0; i<360000; i++))
do
        a=$(((RANDOM%6)+1))
        b=$(((RANDOM%6)+1))
        sum=$(($a+$b))
done
for ((i=1; i<=11; i++))
do
    doublet[$(($i+1))]=$(times[$i])
done
echo "${double[@]}"
double_percentage=$(((1/6)*100))
