#!/bin/bash -x
check=1
randomCheck=$((RANDOM%2))
headValue=0
tailValue=0
count=1
declare -a times
declare -a timesTriplet
declare -A singlet
declare -A doublet
declare -A triplet
while [ $count -gt 0 ]
do
     for ((i=1; i<=5; i++))
     do
         if [ $check -eq $randomCheck ]
         then
              headValue=$(($headValue+1))
              singlet[$(($i+1))]=$headValue
         else
              tailValue=$(($tailValue+1))
              singlet[$(($i+1))]=$tailValue
         fi
      ((count++))
    done
done
echo "${singlet[@]}"
singlet_percentage=$(((1/2)*100))
